In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [23]:
from google.colab import files
upload = files.upload()

Saving heartdisease.csv to heartdisease.csv

In [33]:
df = pd.read_csv('heartdisease.csv', sep='\t')
df.columns = df.columns.str.strip()
df.head()

   Unnamed: 0  age  Gender  Family  diet  Lifestyle  cholestrol  heartdisease
0           0    0       0       1     1          3           0             1
1           1    0       1       1     1          3           0             1
2           2    1       0       0     0          2           1             1
3           3    0       1       0     0          3           2             1

In [34]:
df.shape

(4, 8)

In [35]:
df.isnull().sum()

Unnamed: 0      0
age             0
Gender          0
Family          0
diet            0
Lifestyle       0
cholestrol      0
heartdisease    0
dtype: int64

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    4 non-null      int64
 1   age           4 non-null      int64
 2   Gender        4 non-null      int64
 3   Family        4 non-null      int64
 4   diet          4 non-null      int64
 5   Lifestyle     4 non-null      int64
 6   cholestrol    4 non-null      int64
 7   heartdisease  4 non-null      int64
dtypes: int64(8)
memory usage: 388.0 bytes

In [37]:
df.describe()

,Unnamed: 0,age,Gender,Family,diet,Lifestyle,cholestrol,heartdisease
count,4.000000,4.00,4.00000,4.00000,4.00000,4.00,4.000000,4.0
mean,1.500000,0.25,0.50000,0.50000,0.50000,2.75,0.750000,1.0
std,1.290994,0.50,0.57735,0.57735,0.57735,0.50,0.957427,0.0
min,0.000000,0.00,0.00000,0.00000,0.00000,2.00,0.000000,1.0
25%,0.750000,0.00,0.00000,0.00000,0.00000,2.75,0.000000,1.0
50%,1.500000,0.00,0.50000,0.50000,0.50000,3.00,0.500000,1.0
75%,2.250000,0.25,1.00000,1.00000,1.00000,3.00,1.250000,1.0
max,3.000000,1.00,1.00000,1.00000,1.00000,3.00,2.000000,1.0

In [38]:
df.columns

Index(['Unnamed: 0', 'age', 'Gender', 'Family', 'diet', 'Lifestyle',
       'cholestrol', 'heartdisease'],
      dtype='object')

In [39]:
!pip install pgmpy==1.0.0
import pgmpy
print(pgmpy.__version__)

Requirement already satisfied: pgmpy==1.0.0 in /usr/local/lib/python3.13/dist-packages (1.0.0)
Requirement already satisfied: networkx in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.1.3)
Requirement already satisfied: scipy in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.16.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.1)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.2.3)
Requirement already satisfied: torch in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (2.11.0+cpu)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (0.15.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (4.67.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.6.0)
Requirement already satisfied: opt-einsum in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (3.4.0)
Requirement already satisfied: pyro-ppl in /usr/local/lib/python3.13/dist-packages (from pgmpy==1.0.0) (1.9.1)
Requirement already satisfied: cloudpickle>=3.0 in /usr/local/lib/python3.13/dist-packages (from joblib->pgmpy==1.0.0) (3.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas->pgmpy==1.0.0) (2026.3)
Requirement already satisfied: pyro-api>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from pyro-ppl->pgmpy==1.0.0) (0.1.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.32.5)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (4.16.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (80.10.2)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (1.14.0)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.13/dist-packages (from torch->pgmpy==1.0.0) (2025.12.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn->pgmpy==1.0.0) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.0.3)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (26.3)
Requirement already satisfied: formulaic>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from statsmodels->pgmpy==1.0.0) (1.2.2)
Requirement already satisfied: interface-meta>=1.2.0 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->pgmpy==1.0.0) (2.0.1)
Requirement already satisfied: narwhals>=1.17 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->pgmpy==1.0.0) (2.25.0)
Requirement already satisfied: wrapt>=1.17.0rc1 in /usr/local/lib/python3.13/dist-packages (from formulaic>=1.1.0->statsmodels->pgmpy==1.0.0) (2.4.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas->pgmpy==1.0.0) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from sympy>=1.13.3->torch->pgmpy==1.0.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.13/dist-packages (from jinja2->torch->pgmpy==1.0.0) (3.0.3)
1.0.0

In [40]:
from pgmpy.models import DiscreteBayesianNetwork
from pgmpy.estimators import MaximumLikelihoodEstimator
model = DiscreteBayesianNetwork([
('age', 'heartdisease'),
('Gender', 'heartdisease'),
('Family', 'heartdisease'),
('diet', 'heartdisease'),
('Lifestyle', 'heartdisease'),
('cholestrol', 'heartdisease') ])
mle = MaximumLikelihoodEstimator(model, df)
cpds = mle.get_parameters()
model.add_cpds(*cpds)
print(model.get_cpds('heartdisease'))

+-----------------+---------------+-----+---------------+---------------+
| Family          | Family(0)     | ... | Family(1)     | Family(1)     |
+-----------------+---------------+-----+---------------+---------------+
| Gender          | Gender(0)     | ... | Gender(1)     | Gender(1)     |
+-----------------+---------------+-----+---------------+---------------+
| Lifestyle       | Lifestyle(2)  | ... | Lifestyle(3)  | Lifestyle(3)  |
+-----------------+---------------+-----+---------------+---------------+
| age             | age(0)        | ... | age(1)        | age(1)        |
+-----------------+---------------+-----+---------------+---------------+
| cholestrol      | cholestrol(0) | ... | cholestrol(2) | cholestrol(2) |
+-----------------+---------------+-----+---------------+---------------+
| diet            | diet(0)       | ... | diet(0)       | diet(1)       |
+-----------------+---------------+-----+---------------+---------------+
| heartdisease(1) | 1.0           | ... | 1.0           | 1.0           |
+-----------------+---------------+-----+---------------+---------------+

In [41]:
print(model.get_cpds('age'))

+--------+------+
| age(0) | 0.75 |
+--------+------+
| age(1) | 0.25 |
+--------+------+

In [42]:
print(model.get_cpds('Gender'))

+-----------+-----+
| Gender(0) | 0.5 |
+-----------+-----+
| Gender(1) | 0.5 |
+-----------+-----+

In [43]:
print(model.get_cpds('Family'))

+-----------+-----+
| Family(0) | 0.5 |
+-----------+-----+
| Family(1) | 0.5 |
+-----------+-----+